services:
  - type: web
    region: frankfurt
    name: zep-eu
    autoDeploy: false
    env: image
    image:
      url: ghcr.io/getzep/zep-cloud:latest
    healthCheckPath: /healthz
    envVars:
      # Disable web UI. WARNING: Do not enable this unless
      # you are running Zep on a private network.
      - key: ZEP_SERVER_WEB_ENABLED
        value: false
      - key: PORT
        value: 8000
      - key: ZEP_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres-eu
          property: connectionString
      - key: ZEP_NLP_SERVER_HOSTPORT
        fromService:
          name: zep-nlp-eu
          type: pserv
          property: hostport
      - key: ZEP_OPENAI_API_KEY
        sync: false
  - type: pserv
    region: frankfurt
    name: zep-nlp-eu
    autoDeploy: false
    env: image
    image:
      url: ghcr.io/getzep/zep-nlp-server:latest

databases:
  - name: zep-postgres-eu
    region: frankfurt
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: [] # only allow internal connections
